apiVersion: apps/v1
kind: Deployment
metadata:
  name: npx
  labels:
    app: npx
spec:
  selector:
    matchLabels:
      app: npx
  template:
    metadata:
      labels:
        app: npx
    spec:     
      containers:
      - image: npxhost1
        name: npx        
        imagePullPolicy: Never
        ports:
          - containerPort: 3001
        
---
apiVersion: v1
kind: Service
metadata:
  name: npx
spec:
  ports:
  - name: "npxservice"
    port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: npx
  type: ClusterIP





